services:
  - type: web
    name: skenetic-mail-automation
    env: docker
    plan: free
    image:
      url: n8nio/n8n
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
